name: Parallel Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Say Hello
        run: echo "Hello World from machine ${{ matrix.machine }}!"
